version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=parcheggi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/database_seeding.sql:/docker-entrypoint-initdb.d/database_seeding.sql

  