version: '3.8'

services:
  app:
    build: 
      context: app/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src:/usr/app
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=parcheggi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./database_seeding.sql:/docker-entrypoint-initdb.d/database_seeding.sql